project_id = "fpdxpvkgzrddemldvemg"

[functions.healthz]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-livre-blanc]
verify_jwt = false

[functions.send-contact-confirmation]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-livre-blanc-notification]
verify_jwt = false

[functions.generate-blog-article]
verify_jwt = false