services:
  - type: web
    name: mare-nostrum
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: redirect
        source: /sitemap.xml
        destination: https://fpdxpvkgzrddemldvemg.supabase.co/functions/v1/sitemap
      - type: rewrite
        source: /*
        destination: /index.html
